language: node_js

node_js: 12

cache: npm

install:
  - "npm install"

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE tweet_311_service_test;" -U postgres
  - knex migrate:latest --env test
  - knex seed:run --env test

script:
  - npx lab -l -v **/*.test.js
