language: node_js

node_js:
  - "12"
  - "node"

install:
  - "npm install"

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE tweet_311_service_test;" -U postgres
  - npx sequelize db:migrate --env test
  - npx sequelize db:seed:all --env test

script: npx lab

os:
  - "osx"
