language: node_js

node_js:
  - "12"
  - "node"

install:
  - "npm install"

services:
  - postgresql

env:
- NODE_ENV=test

before_script:
  - psql 'create database tweet_311_service_test;'
  - npx sequelize db:migrate --env test
  - npx sequelize db:seed:all --env test

script: npx lab

os:
  - "osx"
